name: auto-update
run-name: Update npm dependencies

on:
    schedule:
        - cron: "30 12 4,18 * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-deps:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24
                  cache: "npm"

            - name: Update npm dependencies
              run: |
                  npm version patch --no-git-tag-version
                  npm update
                  npm run build
                  npm run test --if-present

            - name: Commit and push changes
              uses: EndBug/add-and-commit@v9
              with:
                  add: "package*.json"
                  message: "Bot: npm deps update"

            - name: Store build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: |
                      dist
                      package*.json

    publish-npm:
        needs: update-deps
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org/

            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build-artifacts

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
